# This workflow will build a Swift project

name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - macOS
          - iOS
        xcode:
          - ^15

    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get swift version
        uses: swift-actions/setup-swift@v2
      - name: Print Swift version
        run: swift --version
      - name: Build & Test
        uses: mxcl/xcodebuild@v3
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
