# This workflow will build a Swift project

name: Build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform:
          - macOS
          - iOS
        xcode:
          - ^15

    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get swift version
        uses: swift-actions/setup-swift@d4537ff835c9778c934e48f78639e270edd5839e # v2.2.0
      - name: Print Swift version
        run: swift --version
      - name: Build & Test
        uses: mxcl/xcodebuild@2cf0ec52b855fa777531c5c89b714caa7a3abd5e # v3.4.0
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
